# Generated by Django 5.0.2 on 2024-03-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='etudiants_id',
        ),
        migrations.AddField(
            model_name='class',
            name='etudiants_id',
            field=models.TextField(default=1, verbose_name='[]'),
            preserve_default=False,
        ),
    ]
