# Generated by Django 5.0.2 on 2024-03-21 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0002_alter_cv_educations_alter_cv_experiences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user_id',
            new_name='user',
        ),
    ]
