# Generated by Django 5.0.2 on 2024-03-14 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0002_remove_user_email_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='content',
        ),
    ]
