# Generated by Django 5.0.2 on 2024-03-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0003_rename_description_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to='PNP.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_profile',
            field=models.FileField(blank=True, default='pdp_default.jpg', null=True, upload_to='avatar/'),
        ),
    ]
