# Generated by Django 5.0.2 on 2024-03-17 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0004_user_friends_alter_user_photo_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='number_of_likes',
        ),
    ]
