# Generated by Django 5.0.2 on 2024-03-10 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0004_room_remove_post_comments_remove_post_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
