# Generated by Django 5.0.2 on 2024-03-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0005_alter_cv_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_of_profile_visits',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
