# Generated by Django 5.0.2 on 2024-03-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0007_rename_user_id_teacher_user_remove_comment_post_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='objects_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='object_id',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
