# Generated by Django 5.0.2 on 2024-03-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0009_alter_cv_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='educations',
            field=models.JSONField(blank=True, default=list, max_length=100),
        ),
        migrations.AlterField(
            model_name='cv',
            name='experiences',
            field=models.JSONField(blank=True, default=list, max_length=100),
        ),
        migrations.AlterField(
            model_name='cv',
            name='skills',
            field=models.JSONField(blank=True, default=list, max_length=100),
        ),
    ]
