# Generated by Django 5.0.2 on 2024-03-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0012_alter_user_cv_alter_user_photo_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='educations',
            field=models.JSONField(blank=True, default=dict, max_length=100),
        ),
        migrations.AlterField(
            model_name='cv',
            name='experiences',
            field=models.JSONField(blank=True, default=dict, max_length=100),
        ),
    ]
