# Generated by Django 5.0.2 on 2024-03-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0013_alter_cv_educations_alter_cv_experiences'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='number_of_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='number_of_replies',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_profile',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to='media/avatar/'),
        ),
    ]
