# Generated by Django 5.0.2 on 2024-03-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0015_alter_cv_educations_alter_cv_experiences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='educations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='cv',
            name='experiences',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
