# Generated by Django 5.0.2 on 2024-03-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0017_alter_cv_languages_alter_cv_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='languages',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cv',
            name='skills',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
