# Generated by Django 5.0.2 on 2024-03-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0018_alter_cv_languages_alter_cv_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cv',
            field=models.FileField(default='cv_default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_profile',
            field=models.FileField(default='default.jpg', upload_to=''),
        ),
    ]
