# Generated by Django 5.0.2 on 2024-03-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0019_alter_user_cv_alter_user_photo_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cv',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_profile',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
