# Generated by Django 5.0.2 on 2024-03-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0022_alter_user_cv_alter_user_photo_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
