# Generated by Django 5.0.2 on 2024-03-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0023_cv_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends_request',
            field=models.ManyToManyField(blank=True, related_name='friends_request', to='PNP.user'),
        ),
    ]
