# Generated by Django 5.0.2 on 2024-03-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0024_user_friends_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='etudiants_id',
        ),
        migrations.AddField(
            model_name='user',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='students', to='PNP.class'),
        ),
        migrations.AddField(
            model_name='user',
            name='introduction',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
