# Generated by Django 5.0.2 on 2024-03-23 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0025_remove_class_etudiants_id_user_classes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='introduction',
        ),
    ]
