# Generated by Django 5.0.3 on 2024-03-25 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0029_class_section_cours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='class',
            name='Section',
        ),
        migrations.RemoveField(
            model_name='class',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='class',
            name='schedule_exams',
        ),
        migrations.RemoveField(
            model_name='class',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='description',
        ),
        migrations.AddField(
            model_name='class',
            name='Degree',
            field=models.TextField(default='Default Degree value', max_length=100),
        ),
        migrations.AddField(
            model_name='class',
            name='Name',
            field=models.CharField(default='Default name value', max_length=100),
        ),
        migrations.AddField(
            model_name='cours',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='cours',
            name='salle',
            field=models.CharField(default='Default salle value', max_length=50),
        ),
        migrations.AddField(
            model_name='cours',
            name='subject',
            field=models.CharField(default='Default subject value', max_length=100),
        ),
        migrations.AlterField(
            model_name='cours',
            name='class_name',
            field=models.CharField(default='Default class name value', max_length=100),
        ),
        migrations.AlterField(
            model_name='cours',
            name='name',
            field=models.CharField(default='Default name value', max_length=100),
        ),
        migrations.AlterField(
            model_name='cours',
            name='teacher',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
