# Generated by Django 5.0.2 on 2024-03-26 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0032_alter_class_degree_alter_class_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='content_type',
        ),
    ]
