# Generated by Django 5.0.2 on 2024-03-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0033_remove_like_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
