# Generated by Django 5.0.2 on 2024-03-27 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0038_room_participent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='participent',
        ),
    ]
