# Generated by Django 5.0.3 on 2024-03-29 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0039_remove_message_participent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='id',
            new_name='class_id',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='Name',
            new_name='class_name',
        ),
    ]
