# Generated by Django 5.0.3 on 2024-03-29 02:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0040_rename_id_class_class_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='students',
            field=models.ManyToManyField(blank=True, editable=False, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
