# Generated by Django 5.0.3 on 2024-03-30 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0041_cours_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='address',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='email',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='name',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='postmedia',
            name='deleted_at',
        ),
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('fichier_joint', models.FileField(blank=True, null=True, upload_to='devoir/')),
                ('date_limite', models.DateTimeField()),
                ('cours', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='PNP.cours')),
            ],
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('fichier_joint', models.FileField(blank=True, null=True, upload_to='documentation/')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PNP.cours')),
            ],
        ),
    ]
