
# Generated by Django 5.0.2 on 2024-03-29 22:24


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0041_cours_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='address',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='email',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='name',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='postmedia',
            name='deleted_at',
        ),


        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PNP.room'),
            preserve_default=False,

        ),
    ]
