# Generated by Django 5.0.2 on 2024-03-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0042_remove_entreprise_address_remove_entreprise_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
