# Generated by Django 5.0.3 on 2024-03-30 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0042_remove_entreprise_address_remove_entreprise_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devoir',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PNP.cours'),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='fichier_joint',
            field=models.FileField(blank=True, null=True, upload_to='creer/devoir/'),
        ),
    ]
