# Generated by Django 5.0.2 on 2024-03-30 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0043_alter_room_description_alter_room_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='messages',
            new_name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PNP.user'),
            preserve_default=False,
        ),
    ]
