# Generated by Django 5.0.2 on 2024-03-30 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0044_rename_messages_message_message_message_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ImageField(blank=True, null=True, upload_to='messages/')),
                ('type', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='media',
        ),
        migrations.AddField(
            model_name='message',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='message', to='PNP.messagemedia'),
        ),
    ]
