# Generated by Django 5.0.2 on 2024-03-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0045_messagemedia_remove_message_media_message_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='groups/'),
        ),
    ]
