# Generated by Django 5.0.3 on 2024-04-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0047_devoir_documentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devoir',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
