# Generated by Django 5.0.3 on 2024-04-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0048_alter_devoir_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
