from .users import User
from .classe import Class
from .teacher import Teacher
from .student import Student
from .entreprise import Entreprise
from .post import Post
from .comment import Comment
from .message import Message
from .room import Room
from .like import Like
from .Cv import Cv
from .postMedia import PostMedia
from .friendsRequest import FriendRequest
from .Cours import Cours
from .messageMedia import MessageMedia
from .devoir import Devoir
from .documentation import Documentation
